# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build

# Include any dependencies generated for this target.
include CMakeFiles/ejecutable.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/ejecutable.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/ejecutable.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/ejecutable.dir/flags.make

CMakeFiles/ejecutable.dir/oscilador.c.o: CMakeFiles/ejecutable.dir/flags.make
CMakeFiles/ejecutable.dir/oscilador.c.o: /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/oscilador.c
CMakeFiles/ejecutable.dir/oscilador.c.o: CMakeFiles/ejecutable.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/ejecutable.dir/oscilador.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/ejecutable.dir/oscilador.c.o -MF CMakeFiles/ejecutable.dir/oscilador.c.o.d -o CMakeFiles/ejecutable.dir/oscilador.c.o -c /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/oscilador.c

CMakeFiles/ejecutable.dir/oscilador.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/ejecutable.dir/oscilador.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/oscilador.c > CMakeFiles/ejecutable.dir/oscilador.c.i

CMakeFiles/ejecutable.dir/oscilador.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/ejecutable.dir/oscilador.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/oscilador.c -o CMakeFiles/ejecutable.dir/oscilador.c.s

# Object files for target ejecutable
ejecutable_OBJECTS = \
"CMakeFiles/ejecutable.dir/oscilador.c.o"

# External object files for target ejecutable
ejecutable_EXTERNAL_OBJECTS =

ejecutable: CMakeFiles/ejecutable.dir/oscilador.c.o
ejecutable: CMakeFiles/ejecutable.dir/build.make
ejecutable: CMakeFiles/ejecutable.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C executable ejecutable"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/ejecutable.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/ejecutable.dir/build: ejecutable
.PHONY : CMakeFiles/ejecutable.dir/build

CMakeFiles/ejecutable.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/ejecutable.dir/cmake_clean.cmake
.PHONY : CMakeFiles/ejecutable.dir/clean

CMakeFiles/ejecutable.dir/depend:
	cd /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build /mnt/c/Users/sofib/OneDrive/Escritorio/proyecto01_sistemas_operativos/build/CMakeFiles/ejecutable.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/ejecutable.dir/depend

